#pragma once

static const char* kMainVertSrc =
"#version 120\n"
"varying vec3 vPosView;\n"
"varying vec3 vNormalView;\n"
"varying vec2 vTexCoord;\n"
"varying vec4 vLightSpacePos;\n"
"varying vec4 vColor;\n"
"uniform mat4 uLightFromView;\n"
"void main() {\n"
"    vec4 viewPos = gl_ModelViewMatrix * gl_Vertex;\n"
"    vPosView = viewPos.xyz;\n"
"    vNormalView = normalize(gl_NormalMatrix * gl_Normal);\n"
"    vTexCoord = gl_MultiTexCoord0.xy;\n"
"    vLightSpacePos = uLightFromView * viewPos;\n"
"    vColor = gl_Color;\n"
"    gl_Position = ftransform();\n"
"}\n";

static const char* kMainFragSrc =
"#version 120\n"
"varying vec3 vPosView;\n"
"varying vec3 vNormalView;\n"
"varying vec2 vTexCoord;\n"
"varying vec4 vLightSpacePos;\n"
"varying vec4 vColor;\n"
"\n"
"uniform sampler2D uTex;\n"
"uniform sampler2D uShadowMap;\n"
"uniform int   uHasTexture;\n"
"uniform vec3  uLightPosView;\n"
"uniform vec3  uLightColor;\n"
"uniform vec3  uAmbient;\n"
"uniform float uShininess;\n"
"uniform float uSpecStrength;\n"
"uniform float uShadowMapTexel;\n"
"uniform int   uReceiveShadow;\n"
"uniform int   uLightEnabled;\n"
"\n"
"uniform int   uFlashOn;\n"
"uniform vec3  uFlashPosView;\n"
"uniform vec3  uFlashDirView;\n"
"uniform vec3  uFlashColor;\n"
"uniform float uFlashCosInner;\n"
"uniform float uFlashCosOuter;\n"
"uniform float uFlashRange;\n"
"\n"
"float rand1(vec2 co) {\n"
"    return fract(sin(dot(co, vec2(12.9898, 78.233))) * 43758.5453);\n"
"}\n"
"\n"
"float computeShadow(vec4 lspos, float NdotL) {\n"
"    if (uReceiveShadow == 0) return 1.0;\n"
"    vec3 proj = lspos.xyz / lspos.w;\n"
"    proj = proj * 0.5 + 0.5;\n"
"    if (proj.z > 1.0 || proj.x < 0.0 || proj.x > 1.0 || proj.y < 0.0 || proj.y > 1.0) return 1.0;\n"
"\n"
"    float bias = max(0.0012 * (1.0 - NdotL), 0.00025);\n"
"\n"
"    float angle = rand1(proj.xy * 1024.0) * 6.2831853;\n"
"    float cs = cos(angle), sn = sin(angle);\n"
"    mat2 rot = mat2(cs, -sn, sn, cs);\n"
"\n"
"    float shadow = 0.0;\n"
"    const float radius = 1.2;\n"
"    for (int x = -2; x <= 2; x++) {\n"
"        for (int y = -2; y <= 2; y++) {\n"
"            vec2 off = rot * (vec2(float(x), float(y)) * radius) * uShadowMapTexel;\n"
"            float depth = texture2D(uShadowMap, proj.xy + off).r;\n"
"            shadow += ((proj.z - bias) > depth) ? 0.0 : 1.0;\n"
"        }\n"
"    }\n"
"    return shadow / 25.0;\n"
"}\n"
"\n"
"void main() {\n"
"    vec4 baseColor = vColor;\n"
"    if (uHasTexture == 1) {\n"
"        vec4 tex = texture2D(uTex, vTexCoord);\n"
"        baseColor *= tex;\n"
"    }\n"
"\n"
"    if (uLightEnabled == 0) {\n"
"        gl_FragColor = baseColor;\n"
"        return;\n"
"    }\n"
"\n"
"    vec3 N = normalize(vNormalView);\n"
"    vec3 V = normalize(-vPosView);\n"
"\n"
"    vec3 L1 = normalize(uLightPosView - vPosView);\n"
"    vec3 H1 = normalize(L1 + V);\n"
"    float NdotL1 = max(dot(N, L1), 0.0);\n"
"    float spec1  = (NdotL1 > 0.0) ? pow(max(dot(N, H1), 0.0), uShininess) : 0.0;\n"
"\n"
"    float shadow = computeShadow(vLightSpacePos, NdotL1);\n"
"    shadow = mix(0.22, 1.0, shadow);\n"
"\n"
"    float dist1 = length(uLightPosView - vPosView);\n"
"    float atten1 = 1.0 / (1.0 + 0.0025 * dist1 + 0.00015 * dist1 * dist1);\n"
"\n"
"    vec3 diffuse1  = uLightColor * NdotL1 * baseColor.rgb * shadow * atten1;\n"
"    vec3 specular1 = uLightColor * spec1  * uSpecStrength * shadow * atten1;\n"
"\n"
"    vec3 diffuse2  = vec3(0.0);\n"
"    vec3 specular2 = vec3(0.0);\n"
"    if (uFlashOn == 1) {\n"
"        vec3 toFrag = vPosView - uFlashPosView;\n"
"        float dist2 = length(toFrag);\n"
"        vec3 L2 = -toFrag / max(dist2, 0.0001);\n"
"        vec3 H2 = normalize(L2 + V);\n"
"        float NdotL2 = max(dot(N, L2), 0.0);\n"
"        float spec2  = (NdotL2 > 0.0) ? pow(max(dot(N, H2), 0.0), uShininess) : 0.0;\n"
"\n"
"        float spotCos = dot(normalize(uFlashDirView), -L2);\n"
"        float cone = smoothstep(uFlashCosOuter, uFlashCosInner, spotCos);\n"
"\n"
"        float ratio = clamp(1.0 - dist2 / uFlashRange, 0.0, 1.0);\n"
"        float range = ratio * ratio;\n"
"\n"
"        float k = cone * range;\n"
"        diffuse2  = uFlashColor * NdotL2 * baseColor.rgb * k;\n"
"        specular2 = uFlashColor * spec2  * uSpecStrength * k;\n"
"    }\n"
"\n"
"    vec3 ambient = uAmbient * baseColor.rgb;\n"
"    vec3 outColor = ambient + diffuse1 + specular1 + diffuse2 + specular2;\n"
"\n"
"    gl_FragColor = vec4(outColor, baseColor.a);\n"
"}\n";

static const char* kDepthVertSrc =
"#version 120\n"
"void main() {\n"
"    gl_Position = ftransform();\n"
"}\n";

static const char* kDepthFragSrc =
"#version 120\n"
"void main() {\n"
"}\n";
